# docker-compose.yml
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bh-store-db
    environment:
      MYSQL_ROOT_PASSWORD: susan429@
      MYSQL_DATABASE: bookhub_store_db    # 생성할 DB 이름
    ports:
      - "3307:3306"                      # 외부 접근용 포트
    networks:
      - bh-network
    volumes:
      - /home/ec2-user/bh-store/db/data:/var/lib/mysql            # 데이터 영속성
      - /home/ec2-user/bh-store/db/init:/docker-entrypoint-initdb.d        # 초기 데이터 주입

  backend:
    image: sojung301/bookhub-store-backend                       # 백엔드 Dockerfile 위치
    container_name: bh-store-app
    environment:
      DB_HOST: bh-store-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: susan429@
      DB_NAME: bookhub_store_db
      FILE_UPLOAD_PATH: /data/images
    depends_on:
      - db
    networks:
      - bh-network
    ports:
      - "8080:8080"                      # 백엔드 포트
    volumes:
      - /home/ec2-user/bh-store/images:/data/images

  front:
    image: sojung301/bookhub-store-front:v2
    container_name: bh-store-front
    environment:
      API_BASE_URL: http://EC2_PUBLIC_IP:8080
    depends_on:
      - backend
    networks:
      - bh-network
    ports:
      - "3000:80"

networks:
  bh-network:
    driver: bridge

